services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ze
            MONGO_INITDB_ROOT_PASSWORD: delivery
        ports:
            - "27017:27017"
        networks:
            - default
    api:
        build: .
        ports:
            - "8080:8080"

        environment:
            DB_USER: ze
            DB_PASS: delivery
            APP_PORT: 8080
        networks:
            - default
networks:
    default:
        driver: bridge
